food_shop/food_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path


# временное решение проблемы отрисовки
# шаблона 404 из коробки
def handler404(request, exception):
    return render(request, '404/404.html', status=404)


handler404 = handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('products.urls')),

]

urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

food_shop/users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from users import views

app_name = 'users'


urlpatterns = [
    path('login/', views.EnterPhoneNumberView.as_view(), name='login'),
    path('login/confirm', views.EnterCodeView.as_view(), name='confirm'),
    path('logout/', views.logout_user, name='logout'),
    path('privacy-policy', TemplateView.as_view(
        template_name='users/privacy_policy.html'), name='privacy-policy'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('resend-code/', views.resend_code, name='resend_code'),
    path('add-address/', views.CreateAddress.as_view(), name='add-address'),
    path('profile/edit/', views.ProfieEditView.as_view(), name='profile-edit'),
]

food_shop/users/models/addresses.py
from django.db import models

from users.models import Profile


class Address(models.Model):
    """Модель для хранения адреса пользователя.

    Поля:

    - client - внешний ключ на модель Пользователь
    - city - город
    - street - улица
    - house_number - номер дома
    - apartment_number - номер квартиры (необязательно)

    Строковое представление содержит поля:
    город, улица, номер дома, номер квартиры (необязательно).
    """
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE,
                                verbose_name='Профиль пользователя',
                                related_name='addresses')
    city = models.CharField(max_length=100, verbose_name='Город')
    street = models.CharField(max_length=100, verbose_name='Улица')
    house_number = models.CharField(max_length=20, verbose_name='Дом')
    apartment_number = models.CharField(max_length=20, verbose_name='Квартира',
                                        blank=True, null=True)

    def __str__(self):
        apartment_str = (f', {self.apartment_number}'
                         if self.apartment_number is not None else '')
        return (f'{self.city}, {self.street},'
                f' {self.house_number}{apartment_str}')

food_shop/users/models/bonuses.py
from decimal import Decimal

from django.db import models

from users.models import Profile


class BonusSystem(models.Model):
    """
    Модель для хранения информации о бонусах пользователя.

    Поля:

    - profile - ссылка на профиль пользователя
    - bonuses_amount - количество бонусов пользователя

    Методы:

    - __str__ - возвращает id объекта
    - add_bonuses_amount - начисляет бонусы на основе стоимости заказа
    - decrease_bonuses_amount - списывает количество используемых бонусов
    """
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE,
                                   verbose_name='Пользователь',
                                   related_name='bonuses')
    bonuses_amount = models.IntegerField(verbose_name='Количество бонусов',
                                         default=0)

    def __str__(self):
        return self.id

    def add_bonuses_amount(self, order_price):
        """
        Yачисляет бонусы на основе стоимости заказа
        """
        if self.profile.orders_price_amount <= 30000:
            self.bonuses_amount += order_price * Decimal('0.10')
        elif self.profile.orders_price_amount <= 45000:
            self.bonuses_amount += order_price * Decimal('0.20')
        self.save()

    def decrease_bonuses_amount(self, count_bonuses_was_used):
        """
        Cписывает количество используемых бонусов
        """
        self.bonuses_amount -= count_bonuses_was_used
        self.save()

food_shop/users/models/clients.py
from django.db import models


class Client(models.Model):
    """Модель пользователя.

    Поля:

    - phone_number - номер телефона
    - last_login - дата и время последнего входа

    Строковое представление содержит телефон пользователя.

    Предоставляет свойство is_authenticated для системы аутентификации.
    """
    phone_number = models.CharField(max_length=12, verbose_name='Телефон')
    last_login = models.DateTimeField(verbose_name='Дата последнего входа',
                                      null=True, blank=True)

    def __str__(self):
        return self.phone_number

    @property
    def is_authenticated(self):
        return True

food_shop/users/models/profiles.py
from django.db import models

from users.models import Client


class Profile(models.Model):
    """Модель профиля пользователя.

    Поля:

    - client - ссылка на модель пользователя
    - name - Имя пользователя
    - sex - Пол пользователя
    - date_of_birthday - День рождения пользователя
    - orders_price_amount - Сумма заказов пользователя

    Методы:

    - __str__ - возвращает id объекта
    - update_orders_price_amount - обновляет общую сумму заказов пользователя
    """
    SEX_CHOISES = (('male', 'мужской'),
                   ('female', 'женский'))
    client = models.OneToOneField(Client, on_delete=models.CASCADE,
                                  verbose_name='Пользователь')
    name = models.CharField(verbose_name='Имя', max_length=50,
                            blank=True, null=True)
    sex = models.CharField(verbose_name='Пол', max_length=10,
                           choices=SEX_CHOISES, default='Не указан')
    date_of_birthday = models.DateField(verbose_name='Дата рождения',
                                        blank=True, null=True)
    orders_price_amount = models.IntegerField(
        verbose_name='Общая сумма заказов', default=0)

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

    def __str__(self):
        return self.id

    def update_orders_price_amount(self, order_price):
        """
        обновляет общую сумму заказов пользователя
        """
        self.orders_price_amount += order_price
        self.save()

food_shop/users/forms/login_forms.py
from django import forms
from django.core.validators import RegexValidator

from users.models import Client


class PhoneNumberForm(forms.ModelForm):
    """Форма для ввода номера телефона пользователя.

    Форма состоит из одного поля phone_number, в которое пользователь
    вводит номер телефона в формате: +79999999999

    Валидация поля:
    - Номер должен начинаться с + и содержать только цифры
    - Длина номера - 12 символов

    При успешной валидации в представлении создаётся или получается объект
    модели Client с введенным номером телефона.
    """
    phone_number = forms.CharField(
        min_length=12, max_length=12,
        label='Номер телефона',
        widget=forms.TextInput(attrs={'placeholder': 'Номер телефона'}),
        validators=[RegexValidator(r'^\+7\d{10}$',
                                   'Номер должен содержать только цифры')])

    class Meta:
        model = Client
        fields = ['phone_number']


class CodeForm(forms.Form):
    """Форма для ввода SMS-кода для авторизации.

    Состоит из одного поля code, куда пользователь вводит код из SMS.

    Валидация поля:
    - Длина кода - 6 цифр
    - Разрешены только цифры

    Форма не сохраняет данные в модель, а лишь
    валидирует корректность введенного кода.
    """
    code = forms.CharField(
        min_length=6, max_length=6,
        label='Код', required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Код из SMS'}),
        validators=[RegexValidator(r'^\d+$',
                                   'Код должен содержать только цифры')])

food_shop/users/views/address_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView

from users.models import Address


class CreateAddress(LoginRequiredMixin, CreateView):
    """
    Представление для созданий адреса доставки пользователя.

    Требует авторизации.

    Использует модель Address.

    Добавить адрес можно на странице оформления заказа, после чего происходит
    редирект обратно к оформлению заказа

    После проверки валидности формы, автоматически подставляет профиль текущего
    пользователя в связанное поле profile
    """
    redirect_field_name = None
    login_url = 'users:login'
    model = Address
    fields = ('city', 'street', 'house_number', 'apartment_number')
    template_name = 'users/add_address.html'
    success_url = reverse_lazy('products:create-order')

    def form_valid(self, form):
        form.instance.profile = self.request.user.profile
        return super().form_valid(form)

food_shop/users/views/client_views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import FormView

from users.forms import CodeForm, PhoneNumberForm
from users.processings import confirm_code, send_code_at_form_valid
from users.tasks import send_confirmation_code_task
from users.utils import generate_confirmation_code


class EnterPhoneNumberView(FormView):
    """Представление для ввода номера телефона.

    Отправляет код подтверждения после валидации формы.
    Перенаправляет авторизованных пользователей на профиль.
    """
    form_class = PhoneNumberForm
    template_name = 'users/enter_phone_number.html'
    success_url = reverse_lazy('users:confirm')

    def form_valid(self, form):
        print('hello')
        send_code_at_form_valid(self.request, form)
        return super().form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('users:profile')
        return super().dispatch(request, *args, **kwargs)


class EnterCodeView(FormView):
    """Представление для ввода кода подтверждения.

    Проверяет наличие номера и кода в сессии.
    Перенаправляет  пользователей без этих данных в сессии
    на страницу ввода номера телефона.
    Перенаправляет авторизованных пользователей на профиль.
    Вызывает confirm_code для авторизации при валидной форме.

    """
    form_class = CodeForm
    template_name = 'users/enter_code.html'
    sucess_url = reverse_lazy('users:profile')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('users:profile')
        if not ('phone_number' in request.session
                and 'code' in request.session):
            return redirect('users:login')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        return confirm_code(self.request, form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        phone_number = self.request.session['phone_number']
        context['phone_number'] = '+7 {} {} {} {}'.format(
            phone_number[2:5], phone_number[5:8],
            phone_number[8:10], phone_number[10:12])
        return context


def resend_code(request):
    """Отправляет повторный код подтверждения на номер из сессии.

    Доступно только для неавторизованных пользователей
    с номером и кодом в сессии.
    Перенаправляет авторизованных пользователей на профиль.
    Перенаправляет  пользователей без кода и номера в сессии
    на страницу ввода номера телефона.
    """
    if request.user.is_authenticated:
        return redirect('users:profile')
    if not ('phone_number' in request.session and 'code' in request.session):
        return redirect('users:login')
    code = generate_confirmation_code()
    phone_number = request.session['phone_number']
    send_confirmation_code_task.delay(phone_number, code)
    request.session['code'] = code
    return HttpResponse('code resend')


@login_required(login_url='users:login', redirect_field_name=None)
def logout_user(request):
    """Выход пользователя из системы.

    Сохраняет данные корзины в сессии после разлогинивания.
    """
    cart_data = request.session.get('cart')
    logout(request)
    request.session['cart'] = cart_data
    return redirect('products:home')

food_shop/users/views/profile_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView

from users.models import Profile


class ProfileView(LoginRequiredMixin, DetailView):
    """
    Представление детального просмотра профиля пользователя.

    Требует авторизации.

    Использует модель Profile.

    Делает выборку полей name, sex, orders_price_amount,
    bonuses__bonuses_amount
    с псевдонимом bonuses_amount.

    Возвращает объект профиля авторизованного пользователя
    """
    login_url = 'users:login'
    redirect_field_name = None
    template_name = 'users/profile.html'
    model = Profile

    def get_object(self, queryset=None):
        return self.model.objects.annotate(
            bonuses_amount=F('bonuses__bonuses_amount')).values(
            'name', 'sex', 'orders_price_amount', 'bonuses_amount').get(
            client=self.request.user)


class ProfieEditView(LoginRequiredMixin, UpdateView):
    """
    Представление для обновления информации профиля пользователя.

    Требует авторизации.

    Использует модель Profile.

    Возвращает объект профиля авторизованного пользователя
    """
    login_url = 'users:login'
    redirect_field_name = None
    model = Profile
    fields = ('name', 'sex', 'date_of_birthday')
    template_name = 'users/update_profile_info.html'
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user.profile

food_shop/templates/users/add_address.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/add_address.css' %}">

<form method="post">
    {% csrf_token %}
    <label for="id_city">Город:</label>
    <input type="text" name="city" id="id_city">

    <label for="id_street">Улица:</label>
    <input type="text" name="street" id="id_street">

    <label for="id_house_number">Дом:</label>
    <input type="text" name="house_number" id="id_house_number">

    <label for="id_apartment_number">Квартира:</label>
    <input type="text" name="apartment_number" id="id_apartment_number">

    <button type="submit">Сохранить</button>
</form>
{% endblock %}

food_shop/templates/users/enter_code.html
{% extends "base.html" %}
{% block title %}
  Авторизация 
{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/enter_code.css' %}">
<div class="center_page">
  <div class="wrapper">
    <b class="entry"> Вход </b>
    <div class="info_text">
      Мы отправили код в SMS на {{phone_number}}
      <br> <a class="back" href="{% url "users:login" %}">Изменить номер </a>
    </div>
    <form method="post" id="code-form">
      {% csrf_token %}
      <div class="form">
        {{ form.code }}
      </div>
      <button type="button" class="resend_code" id="resend-code"> Получить новый код </button>
      <div id="error-container" class="error-container">
        {% if form.errors.code %}
          {{ form.errors.code }}
        {% endif %}
      </div>
      <button type="submit" class="button">Войти</button>
    </form>
    Продолжая, Вы соглашаетесь с условиями
    <br><a class="hidden_decoration" href="{% url 'users:privacy-policy' %}" target="_blank"> Политики обработки персональных данных </a> 
  </div>
</div>

<script>
  document.getElementById('resend-code').addEventListener('click', function() {
    var xhr = new XMLHttpRequest();
    xhr.open('POST', '{% url "users:resend_code" %}');
    xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');
    xhr.onreadystatechange = function() {
      if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {
        console.log('AJAX-запрос успешно завершен');
        document.getElementById('code-form').reset();
        document.getElementById('id_code').value = '';  // Сбросить значение поля ввода
      }
    };

    xhr.send();

    // Дополнительно очистим поле ошибок, если они были видимы
    var errorContainer = document.getElementById('error-container');
    errorContainer.innerHTML = '';
  });
</script>

{% endblock %}

food_shop/templates/users/enter_phone_number.html
{% extends "base.html" %}
{% block title %}
  Авторизация 
{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/enter_phone_number.css' %}">
<div class="center_page">
  <div class="wrapper">
    <b class="entry"> Вход </b>
    <div class="info_text">
      Введите номер телефона, и мы отправим на него
      <br> SMS с кодом для входа
    </div>
    <form method="post">
      {% csrf_token %}
      <div class="form">
        {{ form.phone_number }}
        {% if form.phone_number.errors %}
        <div class="error">
          {{ form.phone_number.errors }}
        </div>
        {% endif %}
      </div>
      <button type="submit" class="button">Получить код</button>
    </form>
    Продолжая, Вы соглашаетесь с условиями
    <br><a class="hidden_decoration" href="{% url 'users:privacy-policy' %}" target="_blank"> Политики обработки персональных данных </a> 
  </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
  var phoneInput = document.getElementById('id_phone_number');
  
  phoneInput.addEventListener('input', function() {
    if (!phoneInput.value.startsWith('+')) {
      phoneInput.value = '+' + phoneInput.value;
    }
  });
});
</script>
{% endblock %}

food_shop/templates/users/privacy_policy.html
Какой-то юридический текст об обработке персональных данных

food_shop/templates/users/profile.html
<!DOCTYPE html>
{% extends "base.html" %}

<head>
    <title>Авторизация</title>
</head>
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
<div class="center">
    <br> Общая сумма заказов: {{object.orders_price_amount}} руб.
    <br> Ваше количество бонусов: {{object.bonuses_amount}}
    <br> Вы можете оплатить бонусами до 70% заказа.
    <br> Чем больше общая сумма заказов, тем больше бонусов вы получаете при оформлении заказов
    <br> Выводить тут ещё какую-то инфу при необходимости
    <br> <a href = {% url 'users:profile-edit'%}> Добавить информацию о себе </a>
</div>
{% endblock content %}

food_shop/templates/users/update_profile_info.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/update_profile.css' %}">
<div class="center">
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить информацию">
</form>
</div>
    {% endblock content %}