food_shop/food_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path


# временное решение проблемы отрисовки
# шаблона 404 из коробки
def handler404(request, exception):
    return render(request, '404/404.html', status=404)


handler404 = handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('products.urls')),

]

urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

food_shop/products/urls.py
from django.urls import include, path, re_path
from django.views.generic import TemplateView

from products import views

app_name = 'products'

products_urls = [
    re_path(r'^products/(?P<category>(pizza|burger|roll))/$',
            views.ProductListView.as_view(), name='product-list'),
    path('product/<slug>/', views.ProductDelaitView.as_view(),
         name='product-detail'),
]

cart_urls = [
    path('cart', views.CartView.as_view(), name='cart'),
    path('add_to_cart/<slug>/', views.add_product_to_cart, name='add_to_cart'),
    path('increase_count/<slug>/', views.increase_product_amount,
         name='increase-count'),
    path('decrease_count/<slug>/', views.decrease_product_amount,
         name='decrease-count'),
    path('cart_clear/', views.clear_cart, name='cart-clear'),
]

order_urls = [
    path('order/', views.OrderView.as_view(), name='create-order'),
    path('order/success-created',
         TemplateView.as_view(
             template_name='products/order_success_created.html'),
         name='order-success-created'),
]
urlpatterns = [
    path('', TemplateView.as_view(template_name='products/home.html'),
         name='home'),
    path('', include(products_urls)),
    path('', include(cart_urls)),
    path('', include(order_urls))
]

food_shop/users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from users import views

app_name = 'users'


urlpatterns = [
    path('login/', views.EnterPhoneNumberView.as_view(), name='login'),
    path('login/confirm', views.EnterCodeView.as_view(), name='confirm'),
    path('logout/', views.logout_user, name='logout'),
    path('privacy-policy', TemplateView.as_view(
        template_name='users/privacy_policy.html'), name='privacy-policy'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('resend-code/', views.resend_code, name='resend_code'),
    path('add-address/', views.CreateAddress.as_view(), name='add-address'),
    path('profile/edit/', views.ProfieEditView.as_view(), name='profile-edit'),
]

food_shop/products/models/orders.py
from django.db import models

from users.models import Address, Profile


class Order(models.Model):
    """
    Модель заказа.

    Поля:

    - profile - ссылка на профиль
    - client_name - имя получателя
    - client_phone_number - телефон получателя
    - client_addressce - ссылка на адрес
    - total_price - общая сумма заказа
    - bonuses_was_used - количетсво использованных бонусов

    Методы:
    - __str__ - возвращает id
    """
    profile = models.ForeignKey(
        Profile, on_delete=models.CASCADE,
        verbose_name='Пользователь сделавший заказ')
    client_name = models.CharField(
        verbose_name='Имя получателя', max_length=25)
    client_phone_number = models.CharField(
        verbose_name='Номер телефона получателя', max_length=25)
    client_address = models.ForeignKey(Address, on_delete=models.DO_NOTHING,
                                       verbose_name='Адрес пользователя')
    total_price = models.IntegerField(verbose_name='Итоговая цена заказа')
    bonuses_was_used = models.IntegerField(
        verbose_name='Сколько использовано бонусов', default=0)

    def __str__(self):
        return self.id

food_shop/products/models/orders_items.py
from django.db import models

from products.models.orders import Order
from products.models.products import Product


class OrderItem(models.Model):
    """
    Модель позиции заказа - связывает заказ и товар.

    Поля:

    - order - ссылка на заказ
    - product - ссылка на товар
    - product_total_price - общая цена товара в заказе
    - product_total_count - общее количество товара

    Методы:

    - __str__ - возвращает id объекта
    """
    order = models.ForeignKey(Order, on_delete=models.CASCADE,
                              verbose_name='Номер заказа')
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING,
                                verbose_name='Номер товара')
    product_total_price = models.IntegerField(
        verbose_name='Общая цена товара одной позиции в заказе')
    product_total_count = models.IntegerField(
        verbose_name='Общее количество товара одной позиции в заказе')

    def __str__(self):
        return self.id

food_shop/products/models/products.py
from PIL import Image

from django.db import models
from django.urls import reverse


class Product(models.Model):
    """
    Модель товара.

    Поля:

    - name - название
    - description - описание
    - weight - вес
    - price - цена
    - image - изображение
    - category - категория
    - slug - url товара
    - available - доступность

    Методы:

    - __str__ - возвращает название продукта
    - save - обработка изображения до размера 300x300 перед сохранением
    - get_absolute_url - получить url товара
    """
    CATEGORY_CHOISES = (('pizza', 'Пицца'),
                        ('roll', 'Ролл'),
                        ('burger', 'Бургер'))

    name = models.CharField(verbose_name='Название продукта', unique=True,
                            max_length=50)
    description = models.TextField(verbose_name='Описание товара')
    weight = models.IntegerField(verbose_name='Вес товара')
    price = models.IntegerField(verbose_name='Цена товара')
    image = models.ImageField(verbose_name='Изображение',
                              upload_to='products/')
    category = models.CharField(verbose_name='Категория товара',
                                choices=CATEGORY_CHOISES, max_length=50)
    slug = models.SlugField(max_length=100, verbose_name='url товара')
    available = models.BooleanField(verbose_name='Есть ли в наличии',
                                    default=True)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        image = Image.open(self.image.path)
        required_size = (300, 300)
        image.thumbnail(required_size)
        image.save(self.image.path)

    def get_absolute_url(self):
        return reverse('products:product-detail',
                       args=[self.slug])

food_shop/products/forms.py
from django import forms

from products.models import Order
from users.models import Address


class OrderForm(forms.ModelForm):
    """Форма создания заказа"""
    client_address = forms.ModelChoiceField(
        queryset=None,
        help_text='город, улица, дом, номер квартиры',
        label='Адрес'
    )

    class Meta:
        model = Order
        exclude = ['profile', 'total_price',]

    def __init__(self, *args, **kwargs):
        """Инициализирует форму заказа.

        При инициализации ограничивает возможные адреса доставки
        только адресами данного пользователя.

        Аргументы:

        * args, kwargs - аргументы, передаваемые в базовый конструктор
        ModelsForm

        Ключевой аргумент:

        * user_profile - профиль пользователя, от имени которого
        создается заказ.

        Если задан аргумент user_profile:

        1. Извлекает его из kwargs

        2. Вызывает базовый конструктор ModelsForm

        3. Ограничивает queryset поля client_address только адресами данного
        пользователя.

        Это гарантирует, что в форме будут доступны для выбора только адреса
        данного пользователя.
        """
        user_profile = kwargs.pop('user_profile', None)
        super().__init__(*args, **kwargs)
        if user_profile is not None:
            self.fields['client_address'].queryset = Address.objects.filter(
                profile=user_profile)

food_shop/products/views/cart_views.py
from django.shortcuts import redirect, render
from django.views import View

from products.cart import Cart
from products.models import Product


class CartView(View):
    """
    Вьюха для отображения корзины пользователя.
    """
    def get(self, request, *args, **kwargs):
        cart = Cart(request)
        return render(request, 'products/cart.html',
                      {'cart': cart.get_products()})


def add_product_to_cart(request, slug):
    """
    Вьюха для добавления товара в корзину
    """
    product = Product.objects.get(slug=slug)
    cart = Cart(request)
    cart.add_product_to_cart(product.slug, product.name, product.price,
                             product.weight, product.image)
    return redirect('products:product-list', category=product.category)


def increase_product_amount(request, slug):
    """
    Вьюха для увеличения количества продукта в корзине
    """
    cart = Cart(request)
    product = Product.objects.get(slug=slug)
    cart.increase_product_amount(slug, product.price)
    return redirect('products:cart')


def decrease_product_amount(request, slug):
    """
    Вьюха для уменьшения количества продукта в корзине
    """
    cart = Cart(request)
    product = Product.objects.get(slug=slug)
    cart.decrease_product_amount(slug, product.price)
    return redirect('products:cart')


def clear_cart(request):
    """
    Вьюха для учистки корзины
    """
    cart = Cart(request)
    cart.clear()
    return redirect('products:cart')

food_shop/products/views/order_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView

from products.cart import Cart
from products.forms import OrderForm
from products.processings import (create_order_and_order_items,
                                  process_bonuses_calculation)
from users.models import BonusSystem


class OrderView(LoginRequiredMixin, CreateView):
    """Представление для создания заказа пользователем.

    Атрибуты:

    - login_url - URL для редиректа при неавторизованном пользователе
    - form_class - используемая форма заказа
    - template_name - шаблон для отображения формы
    - success_url - URL для редиректа при успешном создании заказа

    Методы:

    - get_context_data:
        Добавляет в контекст данные о корзине и бонусах пользователя

    - get_form_kwargs:
        Передает профиль пользователя в форму для фильтрации адресов

    - form_valid:
        Создает заказ из данных формы и корзины
        Обрабатывает использование бонусов
        Перенаправляет на страницу успешного создания
    """
    login_url = 'users:login'
    form_class = OrderForm
    template_name = 'products/order_create.html'
    success_url = reverse_lazy('products:order-success-created')

    def get_context_data(self, **kwargs):
        """
        Добавляет в контекст данные о товаре в корзине,
        количестве бонусов пользователя и общую сумму товаров.
        """
        context = super().get_context_data(**kwargs)
        cart = Cart(self.request)
        context['bonuses_count'] = BonusSystem.objects.get(
            profile=self.request.user.profile).bonuses_amount
        context['items_in_cart'] = cart.get_products()
        context['total_price'] = cart.get_total_price()
        return context

    def get_form_kwargs(self):
        """
        Передает профиль пользователя в форму для фильтрации адресов.
        """
        kwargs = super().get_form_kwargs()
        kwargs['user_profile'] = self.request.user.profile
        return kwargs

    def form_valid(self, form):
        """
        Создает заказ из данных формы и корзины.
        Обрабатывает использование бонусов.
        Перенаправляет на страницу успешного создания заказа.
        """
        cart = Cart(self.request)
        process_bonuses_calculation(cart, form, self.request.user)
        create_order_and_order_items(cart, form)
        return super().form_valid(form)

food_shop/products/views/product_views.py
from django.views.generic import DetailView, ListView

from products.models import Product


class ProductListView(ListView):
    """
    Представление для отображения списка товаров определенной категории.

    Атрибуты:

    - model - модель Product
    - template_name - имя шаблона списка
    - context_object_name - имя списка в контексте шаблона

    Методы:

    - get_queryset() - фильтрует товары по категории и доступности.

    """
    model = Product
    template_name = 'products/product_list.html'
    context_object_name = 'products'

    def get_queryset(self):
        return self.model.objects.filter(category=self.kwargs['category'],
                                         available=True)


class ProductDelaitView(DetailView):
    """
    Представление для отображения детальной информации о товаре.

    Атрибуты:

    - model - модель Product
    - context_object_name - имя объекта товара в контексте
    - template_name - имя шаблона детальной страницы
    - queryset - запрос на получение товара по параметру slug

    Отображает детальную страницу выбранного товара.

    """
    model = Product
    context_object_name = 'product'
    template_name = 'products/product_detail.html'
    queryset = model.objects.all()

food_shop/templates/products/cart.html
<!DOCTYPE html>
{% extends 'base.html' %}
<html>
<head>
    <title>Cart</title>
</head>

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
    <h1>Корзина</h1>
    <div class="product-container">
        {% if cart %}
            {% for product_slug, product in cart %}
                <div class="product">
                    <img src="{{ product.image }}">
                    <h2>{{ product.name }}</h2>
                    <p> Цена: {{ product.price }}</p>
                    <p> Вес: {{ product.weight }}</p>
                    <p> Количество: {{product.count}} </p>
                      <a class="no_decor" href="{% url 'products:increase-count' product_slug %}"> Больше </a>
                      <a class="no_decor" href="{% url 'products:decrease-count' product_slug %}"> Меньше </a>
                </div>
            {% endfor %}
        </div>
        <a class="buttons" href="{% url 'products:create-order' %}"> Оформить заказ</a> 
        <a class="buttons" href="{% url 'products:cart-clear' %}"> Очистить корзину</a> 
        {% else %}
            <p class="cart_empty">Ваша корзина пустая</p>
        {% endif %}
{% endblock %}
</html>

food_shop/templates/products/home.html
{% extends "base.html" %}
{% block content %}
<style>
    .main_page_text {
        text-align: center;
    }
</style>

{% load static %}
<div class="main_page_text">
Какое-то оформление
</div>
{% endblock %}

food_shop/templates/products/order_create.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/order_create.css' %}">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> 
<script>
$(document).ready(function() {

  $('#id_use_bonuses').on('change', function() {
    if ($(this).prop('checked')) {
      $('.slider-container').show();
      $('#bonuses-used-info').show();
    } else {
      $('.slider-container').hide();
      $('#bonuses-used-info').hide();
    }
    calculateTotalPrice();
  });

  $('#id_bonuses_was_used').on('input', function() {
    calculateTotalPrice();
  });

  function calculateTotalPrice() {
    var bonusesUsedPercent = 0;
    if ($('#id_use_bonuses').prop('checked')) {
      bonusesUsedPercent = parseInt($('#id_bonuses_was_used').val());
    }
    var total_price = parseInt('{{ total_price }}');
    var maxBonusesPercent = Math.min(70, Math.floor({{ bonuses_count }} / total_price * 100));
    var bonusesUsed = Math.min(Math.floor(total_price * bonusesUsedPercent / 100), Math.floor({{ bonuses_count }}));
    $('#id_bonuses_was_used').attr('max', maxBonusesPercent);
    $('#bonus-value').text(bonusesUsedPercent + '%');

    var bonusesUsedInfo = 'Задействовано бонусов: ' + bonusesUsed + ' руб.';
    $('#bonuses-used-info').text(bonusesUsedPercent > 0 ? bonusesUsedInfo : '');
    var totalPriceWithBonuses = total_price - bonusesUsed;
    $('#total_price').text(totalPriceWithBonuses.toFixed(2) + ' руб.');
    $('#bonuses-used-hidden').val(bonusesUsed);
  }


  calculateTotalPrice();


  $('form').on('submit', function(e) {

    calculateTotalPrice();

    return true;
  });

  // Добавляем вывод общего количества бонусов у пользователя
  $('#id_use_bonuses').on('change', function() {
    if ($(this).prop('checked')) {
      var totalBonuses = parseInt('{{ bonuses_count }}');
      $('#user-bonuses-count-info').text('Ваше общее количество бонусов: ' + totalBonuses + ' руб.').show();
    } else {
      $('#user-bonuses-count-info').hide();
    }
  });
});
</script>
<div class="margin_block">
  <div class="container">
    <div class="left-block">
      <form method="post">
        {% csrf_token %}
        <br>{{form.client_name.label}}
        <br>{{form.client_name}}
        <br>{{form.client_phone_number.label}}
        <br>{{form.client_phone_number}}
        <br>{{ form.client_address.label }}
        <br>{{ form.client_address }}
        <a href = {% url 'users:add-address'%}> Добавить адрес </a>
        <br>{% if bonuses_count > 0 %}
        <br><label for="id_use_bonuses">Использовать бонусы?</label>
        <input type="checkbox" id="id_use_bonuses">  
        <div class="slider-container" style="display: none;">  
          <input type="range" min="0" max="100" step="1" id="id_bonuses_was_used" value="0"> 
          <span id="bonus-value">0%</span>  
        </div>
        {% endif %}
        <br><button type="submit" class="button">Оформить заказ</button>
        <input type="hidden" name="bonuses_was_used" id="bonuses-used-hidden">
      </form>
    </div>
    <div class="right-block">
      Выводим тут например инфу о товарах в которые сейчас в корзине
      <br> <span id="user-bonuses-count-info" style="display: none;"></span> 
      <br> <span id="bonuses-used-info" style="display: none;"></span>  
      <br> Итоговая цена заказа: <span id="total_price">{{ total_price }} руб.</span>
    </div>
  </div>
</div>
{% endblock %}

food_shop/templates/products/order_success_created.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/order_success_created.css' %}">
<div class="center">
  Заказ успешно оформлен
  <br><a class="links" href = {% url 'products:home'%}> Главная </a>
  <a class="links" href = {% url 'products:cart'%}> Корзина </a>
</div>

{% endblock %}

food_shop/templates/products/product_detail.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/product_detail.css' %}">
<div class="center_page">
  <h1 class="category_name"> {{ category }} </h1>
    <div class="product-image">
    <img src="{{ product.image.url }}" alt="{{ product.name }}" width="300" height="300">
    </div>
    <div class="product-name">
    {{ product.name }}
    </div>
    <div class="product-description">
        {{ product.description }}
    </div>
    <div class="product-price">
        Вес: {{product.weight}} г.
        <br> Цена: {{ product.price }} руб.
    </div>
    <a class="add_to_cart" href={% url 'products:add_to_cart' product.slug %}> добавить в корзину</a>
    <a class="product-details-link" href="javascript:history.back()"> Вернуться назад </a>
</div>
{% endblock %}

food_shop/templates/products/product_list.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/product_list.css' %}">
<div class="center_page">
    <div class="product-container">
    {% for product in products %}
    <div class="product">
        <div class="product-image">
        <img src="{{ product.image.url}}">
        </div>
        <div class="product-name">
        {{ product.name }}
        </div>
        <div class="product-description">
        {% if product.description|length > 90 %}
            {{ product.description|slice:":90" }}...
        {% else %}
            {{ product.description }}
        {% endif %}
        </div>
        <div class="product-price">
          Вес: {{product.weight}} г.
          <br> Цена: {{ product.price }} руб.
        </div>
        <a class="product-details-link" href="{{ product.get_absolute_url }}"> Подробнее </a>
    </div>
    {% endfor %}
    </div>
</div>
{% endblock %}