food_shop/food_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path


# временное решение проблемы отрисовки
# шаблона 404 из коробки
def handler404(request, exception):
    return render(request, '404/404.html', status=404)


handler404 = handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('products.urls')),

]

urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

food_shop/products/urls.py
from django.urls import include, path, re_path
from django.views.generic import TemplateView

from products import views

app_name = 'products'

products_urls = [
    re_path(r'^products/(?P<category>(pizza|burger|roll))/$',
            views.ProductListView.as_view(), name='product-list'),
    path('product/<slug>/', views.ProductDelaitView.as_view(),
         name='product-detail'),
]

cart_urls = [
    path('cart', views.CartView.as_view(), name='cart'),
    path('add_to_cart/<slug>/', views.add_product_to_cart, name='add_to_cart'),
    path('increase_count/<slug>/', views.increase_product_amount,
         name='increase-count'),
    path('decrease_count/<slug>/', views.decrease_product_amount,
         name='decrease-count'),
    path('cart_clear/', views.clear_cart, name='cart-clear'),
]

order_urls = [
    path('order/', views.OrderView.as_view(), name='create-order'),
    path('order/success-created',
         TemplateView.as_view(
             template_name='products/order_success_created.html'),
         name='order-success-created'),
]
urlpatterns = [
    path('', TemplateView.as_view(template_name='products/home.html'),
         name='home'),
    path('', include(products_urls)),
    path('', include(cart_urls)),
    path('', include(order_urls))
]

food_shop/users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from users import views

app_name = 'users'


urlpatterns = [
    path('login/', views.EnterPhoneNumberView.as_view(), name='login'),
    path('login/confirm', views.EnterCodeView.as_view(), name='confirm'),
    path('logout/', views.logout_user, name='logout'),
    path('privacy-policy', TemplateView.as_view(
        template_name='users/privacy_policy.html'), name='privacy-policy'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('resend-code/', views.resend_code, name='resend_code'),
    path('add-address/', views.CreateAddress.as_view(), name='add-address'),
    path('profile/edit/', views.ProfieEditView.as_view(), name='profile-edit'),
]

food_shop/templates/includes/header.html
{%load static%}
<link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">
  <header class="header">
    <a class="a__logo" href = "/"> FOOD SHOP </a> 
    <a class="a__cart_login" href = {% url 'products:cart'%}> корзина </a>
    {% if user.is_authenticated %}
      <a class="a__cart_login" href = {% url 'users:logout'%}> Выйти </a> 
    {% else %}
      <a class="a__cart_login" href = {% url 'users:login'%}> Войти </a>
    {% endif %}
  </header>

food_shop/templates/includes/left_panel.html
{%load static%}
<link rel="stylesheet" type="text/css" href="{% static 'css/left_panel.css' %}">

<div class="sidenav">
  <a href= {% url 'products:product-list' category='pizza' %}>Пицца</a>
  <a href= {% url 'products:product-list' category='roll' %}>Суши</a>
  <a href= {% url 'products:product-list' category='burger' %}>Бургеры</a>
</div>
  